// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP39g32wAKR1UhkPI_J0IjwTx2G2boh6o',
    appId: '1:953607517126:web:7f2594d3bd57fd13a038c7',
    messagingSenderId: '953607517126',
    projectId: 'chatapp-11a00',
    authDomain: 'chatapp-11a00.firebaseapp.com',
    storageBucket: 'chatapp-11a00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA31o7B0l6FFYsya2YvbDGgREnQQTwrdHc',
    appId: '1:953607517126:android:a38f254453a2a7d9a038c7',
    messagingSenderId: '953607517126',
    projectId: 'chatapp-11a00',
    storageBucket: 'chatapp-11a00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcVOGXvjS7jB-XC9oui8k1ysmrsWQauQQ',
    appId: '1:953607517126:ios:ea1e017f707c97cba038c7',
    messagingSenderId: '953607517126',
    projectId: 'chatapp-11a00',
    storageBucket: 'chatapp-11a00.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcVOGXvjS7jB-XC9oui8k1ysmrsWQauQQ',
    appId: '1:953607517126:ios:ea1e017f707c97cba038c7',
    messagingSenderId: '953607517126',
    projectId: 'chatapp-11a00',
    storageBucket: 'chatapp-11a00.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP39g32wAKR1UhkPI_J0IjwTx2G2boh6o',
    appId: '1:953607517126:web:0f4194564ec5c11ea038c7',
    messagingSenderId: '953607517126',
    projectId: 'chatapp-11a00',
    authDomain: 'chatapp-11a00.firebaseapp.com',
    storageBucket: 'chatapp-11a00.firebasestorage.app',
  );
}
